language: generic 
sudo: required
servies:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t frontend-test .
script:
  - docker run -e CI=true frontend-test yarn test   
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "React-docker"
  env: "Reactdocker-env"
  bucker_name: "atifact"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
