sudo: required
language: generic 
servies:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t frontend-test .
  - docker run -p 3000:3000  frontend-test
script:
  - docker run -e CI=true frontend yarn test   
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "React-docker"
  env: "Reactdocker-env"
  bucker_name: "atifact"
  on:
    branch: main
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
